name: Release

on:
  push:
    tags:
      - "v*"

jobs:

  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v1

      - name: Sync
        run: uv sync

      - name: Build
        run: uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kubesentinel
          path: dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*